# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('', 'Selecione    Cargo '), ('Auditor (a)', 'Auditor (a)'), ('Cotizador (a)', 'Cotizador (a)'), ('Contador (a)', 'Contador (a)'), ('Enc. Almacenes', 'Enc. Almacenes'), ('Enc. Area Tecnica', 'Enc. Area Tecnica'), ('Enc. Bienes', 'Enc. Bienes'), ('Enc. R. Humanos ', 'Enc. R. Humanos '), ('Enc. Tesoreria', 'Enc. Tesoreria'), ('Enc. Soldaduria', 'Enc. Soldaduria'), ('Gerente General', 'Gerente General'), ('Ing. de Sistemas', 'Ing. de Sistemas'), ('Mecanico', 'Mecanico'), ('Resp. Archivos', 'Resp. Archivos'), ('Secretaria', 'Secretaria'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.Departamento')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['cargo'],
            },
        ),
    ]
